package sistema_experto;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

public class c_interfazUsuario extends javax.swing.JFrame {
    private c_moduloJustificacion o_modJustificacion;
    private c_moduloSintomas o_modSintomas;
    private c_moduloActualizacion o_modActualizacion;
    private c_motorInferencia o_motInferencia;
    private c_interfazTratamiento o_intTratamiento;
    private ArrayList a_Estrategia;
    private String mostrarReglas;
    
    public c_interfazUsuario() {
        initComponents();        
        o_modJustificacion = new c_moduloJustificacion();
        o_modSintomas = new c_moduloSintomas();
        o_modActualizacion = new c_moduloActualizacion();
        o_motInferencia = new c_motorInferencia();
        mostrarReglas=o_modActualizacion.m_mostrarBaseConocimiento();
        a_txtaReglas.setText(mostrarReglas);
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/img_icono.png")).getImage());// Nos permite modificar el icono de la ventana.
        setLocationRelativeTo(null);                                            // Centra la ventana
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Interfaz = new javax.swing.JPanel();
        a_lblTitulo = new javax.swing.JLabel();
        a_lblIcono = new javax.swing.JLabel();
        a_lblReglas = new javax.swing.JLabel();
        a_btnAgregar = new javax.swing.JButton();
        a_btnEliminar = new javax.swing.JButton();
        a_btnModificar = new javax.swing.JButton();
        a_scrlReglas = new javax.swing.JScrollPane();
        a_txtaReglas = new javax.swing.JTextArea();
        a_lblJustificacion = new javax.swing.JLabel();
        a_lblProceso = new javax.swing.JLabel();
        a_scrlEstrategia = new javax.swing.JScrollPane();
        a_tblEstrategia = new javax.swing.JTable();
        a_scrlJustificacion = new javax.swing.JScrollPane();
        a_txtaJustificacion = new javax.swing.JTextArea();
        a_btnSintoma = new javax.swing.JButton();
        a_lblDiagnostico = new javax.swing.JLabel();
        a_menuBar = new javax.swing.JMenuBar();
        a_menuSintoma = new javax.swing.JMenu();
        a_menuItemSintAgregar = new javax.swing.JMenuItem();
        a_menuItemSintMostrar = new javax.swing.JMenuItem();
        a_menuItemSintEliminar = new javax.swing.JMenuItem();
        a_menuTratamiento = new javax.swing.JMenu();
        a_menuItemTratAgregar = new javax.swing.JMenuItem();
        a_menuItemTratEliminar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Experto para la Detección de Trastornos de Ansiedad");

        pnl_Interfaz.setForeground(new java.awt.Color(102, 153, 255));

        a_lblTitulo.setBackground(new java.awt.Color(102, 153, 255));
        a_lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        a_lblTitulo.setText("Sistema Experto para la Detección de Trastornos de Ansiedad");

        a_lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/img_psicologia.png"))); // NOI18N

        a_lblReglas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a_lblReglas.setText("Reglas");

        a_btnAgregar.setText("Agregar");
        a_btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_btnAgregarActionPerformed(evt);
            }
        });

        a_btnEliminar.setText("Eliminar");
        a_btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_btnEliminarActionPerformed(evt);
            }
        });

        a_btnModificar.setText("Modificar");
        a_btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_btnModificarActionPerformed(evt);
            }
        });

        a_txtaReglas.setEditable(false);
        a_txtaReglas.setColumns(20);
        a_txtaReglas.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        a_txtaReglas.setRows(5);
        a_txtaReglas.setText(mostrarReglas);
        a_scrlReglas.setViewportView(a_txtaReglas);

        a_lblJustificacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a_lblJustificacion.setText("Justificación:");

        a_lblProceso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a_lblProceso.setText("Proceso");

        a_tblEstrategia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        a_scrlEstrategia.setViewportView(a_tblEstrategia);

        a_txtaJustificacion.setEditable(false);
        a_txtaJustificacion.setColumns(20);
        a_txtaJustificacion.setRows(5);
        a_scrlJustificacion.setViewportView(a_txtaJustificacion);

        a_btnSintoma.setText("Diagnosticar");
        a_btnSintoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_btnSintomaActionPerformed(evt);
            }
        });

        a_lblDiagnostico.setText("Diagnóstico:");

        javax.swing.GroupLayout pnl_InterfazLayout = new javax.swing.GroupLayout(pnl_Interfaz);
        pnl_Interfaz.setLayout(pnl_InterfazLayout);
        pnl_InterfazLayout.setHorizontalGroup(
            pnl_InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_InterfazLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_InterfazLayout.createSequentialGroup()
                        .addGroup(pnl_InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pnl_InterfazLayout.createSequentialGroup()
                                    .addComponent(a_btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(a_btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(a_btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(a_scrlReglas, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a_lblReglas, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(a_scrlEstrategia)
                            .addGroup(pnl_InterfazLayout.createSequentialGroup()
                                .addComponent(a_lblProceso)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_InterfazLayout.createSequentialGroup()
                                .addComponent(a_lblDiagnostico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(a_btnSintoma, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(a_scrlJustificacion)
                    .addGroup(pnl_InterfazLayout.createSequentialGroup()
                        .addGroup(pnl_InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_InterfazLayout.createSequentialGroup()
                                .addComponent(a_lblIcono)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(a_lblTitulo))
                            .addComponent(a_lblJustificacion))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_InterfazLayout.setVerticalGroup(
            pnl_InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_InterfazLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_InterfazLayout.createSequentialGroup()
                        .addComponent(a_lblIcono)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_InterfazLayout.createSequentialGroup()
                        .addComponent(a_lblTitulo)
                        .addGap(32, 32, 32)))
                .addGroup(pnl_InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a_lblReglas)
                    .addComponent(a_lblProceso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a_scrlEstrategia, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(a_scrlReglas, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(pnl_InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a_btnAgregar)
                    .addComponent(a_btnModificar)
                    .addComponent(a_btnEliminar)
                    .addComponent(a_btnSintoma)
                    .addComponent(a_lblDiagnostico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a_lblJustificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a_scrlJustificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );

        a_menuSintoma.setText("Síntomas");

        a_menuItemSintAgregar.setText("Agregar Sintoma");
        a_menuItemSintAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_menuItemSintAgregarActionPerformed(evt);
            }
        });
        a_menuSintoma.add(a_menuItemSintAgregar);

        a_menuItemSintMostrar.setText("Mostrar Sintomas");
        a_menuItemSintMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_menuItemSintMostrarActionPerformed(evt);
            }
        });
        a_menuSintoma.add(a_menuItemSintMostrar);

        a_menuItemSintEliminar.setText("Eliminar Sintoma");
        a_menuItemSintEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_menuItemSintEliminarActionPerformed(evt);
            }
        });
        a_menuSintoma.add(a_menuItemSintEliminar);

        a_menuBar.add(a_menuSintoma);

        a_menuTratamiento.setText("Tratamientos");

        a_menuItemTratAgregar.setText("Agregar Tratamiento");
        a_menuItemTratAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_menuItemTratAgregarActionPerformed(evt);
            }
        });
        a_menuTratamiento.add(a_menuItemTratAgregar);

        a_menuItemTratEliminar.setText("Eliminar Tratamiento");
        a_menuItemTratEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_menuItemTratEliminarActionPerformed(evt);
            }
        });
        a_menuTratamiento.add(a_menuItemTratEliminar);

        a_menuBar.add(a_menuTratamiento);

        setJMenuBar(a_menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Interfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Interfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_llenaTabla(){
        a_Estrategia = o_motInferencia.m_getEstrategia();
        String[] v_tblModel=new String[]{"Ciclo","BH","Conjunto Conflicto","Resolucion"};
        DefaultTableModel v_Modelo=new DefaultTableModel(null,v_tblModel);
        a_tblEstrategia.setModel(v_Modelo);
        String[] v_Datos={"","","",""};
        String v_Ciclo[] = new String[3];
        for (int i = 0; i < a_Estrategia.size(); i++) {
            v_Ciclo=(String[])a_Estrategia.get(i);
            v_Datos[0]=""+(i+1);
            v_Datos[1]=v_Ciclo[0];
            v_Datos[2]=v_Ciclo[1];
            v_Datos[3]=v_Ciclo[2];
            v_Modelo.addRow(v_Datos);
        }
    }
    
    private void a_btnSintomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_btnSintomaActionPerformed
        char v_Diagnostico = o_motInferencia.m_encadenamientoAdelante();
        a_lblDiagnostico.setText("Diagnóstico: "+o_modSintomas.m_BuscaSintoma(v_Diagnostico));
        a_txtaJustificacion.setText(o_modJustificacion.m_BuscaTratamiento(v_Diagnostico));
        m_llenaTabla();
    }//GEN-LAST:event_a_btnSintomaActionPerformed

    private void a_btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_btnAgregarActionPerformed
        o_modActualizacion.m_insertarBaseConocimiento();
        mostrarReglas=o_modActualizacion.m_mostrarBaseConocimiento();
        a_txtaReglas.setText("");
        a_txtaReglas.setText(mostrarReglas);
    }//GEN-LAST:event_a_btnAgregarActionPerformed

    private void a_btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_btnEliminarActionPerformed
        o_modActualizacion.m_eliminarBaseConocimiento();
        mostrarReglas=o_modActualizacion.m_mostrarBaseConocimiento();
        a_txtaReglas.setText("");
        a_txtaReglas.setText(mostrarReglas);
    }//GEN-LAST:event_a_btnEliminarActionPerformed

    private void a_btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_btnModificarActionPerformed
        o_modActualizacion.m_modificaBaseConocimiento();
        mostrarReglas=o_modActualizacion.m_mostrarBaseConocimiento();
        a_txtaReglas.setText("");
        a_txtaReglas.setText(mostrarReglas);
    }//GEN-LAST:event_a_btnModificarActionPerformed

    private void a_menuItemSintAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_menuItemSintAgregarActionPerformed
        o_modSintomas.m_AgregarSintoma();
    }//GEN-LAST:event_a_menuItemSintAgregarActionPerformed

    private void a_menuItemSintMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_menuItemSintMostrarActionPerformed
        o_modSintomas.m_MostrarSintomas();
    }//GEN-LAST:event_a_menuItemSintMostrarActionPerformed

    private void a_menuItemSintEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_menuItemSintEliminarActionPerformed
        
    }//GEN-LAST:event_a_menuItemSintEliminarActionPerformed

    private void a_menuItemTratAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_menuItemTratAgregarActionPerformed
        o_intTratamiento = new c_interfazTratamiento();
    }//GEN-LAST:event_a_menuItemTratAgregarActionPerformed

    private void a_menuItemTratEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_menuItemTratEliminarActionPerformed
        
    }//GEN-LAST:event_a_menuItemTratEliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a_btnAgregar;
    private javax.swing.JButton a_btnEliminar;
    private javax.swing.JButton a_btnModificar;
    private javax.swing.JButton a_btnSintoma;
    private javax.swing.JLabel a_lblDiagnostico;
    private javax.swing.JLabel a_lblIcono;
    private javax.swing.JLabel a_lblJustificacion;
    private javax.swing.JLabel a_lblProceso;
    private javax.swing.JLabel a_lblReglas;
    private javax.swing.JLabel a_lblTitulo;
    private javax.swing.JMenuBar a_menuBar;
    private javax.swing.JMenuItem a_menuItemSintAgregar;
    private javax.swing.JMenuItem a_menuItemSintEliminar;
    private javax.swing.JMenuItem a_menuItemSintMostrar;
    private javax.swing.JMenuItem a_menuItemTratAgregar;
    private javax.swing.JMenuItem a_menuItemTratEliminar;
    private javax.swing.JMenu a_menuSintoma;
    private javax.swing.JMenu a_menuTratamiento;
    private javax.swing.JScrollPane a_scrlEstrategia;
    private javax.swing.JScrollPane a_scrlJustificacion;
    private javax.swing.JScrollPane a_scrlReglas;
    private javax.swing.JTable a_tblEstrategia;
    private javax.swing.JTextArea a_txtaJustificacion;
    private javax.swing.JTextArea a_txtaReglas;
    private javax.swing.JPanel pnl_Interfaz;
    // End of variables declaration//GEN-END:variables
}
